-- 
-- require 'wrap'
---

local interface = wrap.CInterface.new()

-- special argument specific to torch package
interface.argtypes.LongArg = {

   vararg = true,

   helpname = function(arg)
               return "(LongStorage | dim1 [dim2...])"
            end,

   declare = function(arg)
              return string.format("THLongStorage *arg%d = NULL;", arg.i)
           end,

   init = function(arg)
             if arg.default then
                error('LongArg cannot have a default value')
             end
          end,
   
   check = function(arg, idx)
            return string.format("torch_islongargs(L, %d)", idx)
         end,

   read = function(arg, idx)
             return string.format("arg%d = torch_checklongargs(L, %d);", arg.i, idx)
          end,
   
   carg = function(arg, idx)
             return string.format('arg%d', arg.i)
          end,

   creturn = function(arg, idx)
                return string.format('arg%d', arg.i)
             end,
   
   precall = function(arg)
                local txt = {}
                if arg.returned then
                   table.insert(txt, string.format('luaT_pushudata(L, arg%d, torch_LongStorage_id);', arg.i))
                end
                return table.concat(txt, '\n')
             end,

   postcall = function(arg)
                 local txt = {}
                 if arg.creturned then
                    -- this next line is actually debatable
                    table.insert(txt, string.format('THLongStorage_retain(arg%d);', arg.i))
                    table.insert(txt, string.format('luaT_pushudata(L, arg%d, torch_LongStorage_id);', arg.i))
                 end
                 if not arg.returned and not arg.creturned then
                    table.insert(txt, string.format('THLongStorage_free(arg%d);', arg.i))
                 end
                 return table.concat(txt, '\n')
              end   
}

-- also specific to torch: we generate a 'dispatch' function
-- first we create a helper function
interface:print([[
static const void* torch_istensorid(lua_State *L, const void *id)
{
  if(!id)
    return NULL;

  luaT_pushmetaclass(L, id);
  lua_pushstring(L, "torch");
  lua_rawget(L, -2);
  if(lua_istable(L, -1))
    return id;
  else
  {
    lua_pop(L, 2);
    return NULL;
  }

  return NULL;
}
]])

interface.dispatchregistry = {}
function interface:wrap(name, ...)
   -- usual stuff
   wrap.CInterface.wrap(self, name, ...)

   -- dispatch function
   if not interface.dispatchregistry[name] then
      interface.dispatchregistry[name] = true
      table.insert(interface.dispatchregistry, {name=name, wrapname=string.format("torch_%s", name)})

      interface:print(string.gsub([[
static int torch_NAME(lua_State *L)
{
  int narg = lua_gettop(L);
  const void *id;

  if(narg < 1 || !(id = torch_istensorid(L, luaT_id(L, 1)))) /* first argument is tensor? */
  {
    if(narg < 2 || !(id = torch_istensorid(L, luaT_id(L, 2)))) /* second? */
    {
      if(lua_isstring(L, -1) && (id = torch_istensorid(L, luaT_typename2id(L, lua_tostring(L, -1))))) /* do we have a valid string then? */
        lua_pop(L, 1);
      else if(!(id = torch_istensorid(L, torch_getdefaulttensorid())))
        luaL_error(L, "internal error: the default tensor type does not seem to be an actual tensor");
    }
  }
  
  lua_pushstring(L, "NAME");
  lua_rawget(L, -2);
  if(lua_isfunction(L, -1))
  {
    lua_insert(L, 1);
    lua_pop(L, 2); /* the two tables we put on the stack above */
    lua_call(L, lua_gettop(L)-1, LUA_MULTRET);
  }
  else
    return luaL_error(L, "%s does not implement the torch.NAME() function", luaT_id2typename(L, id));

  return lua_gettop(L);
}
]], 'NAME', name))
  end
end

function interface:dispatchregister(name)
   local txt = self.txt
   table.insert(txt, string.format('static const struct luaL_Reg %s [] = {', name))
   for _,reg in ipairs(self.dispatchregistry) do
      table.insert(txt, string.format('{"%s", %s},', reg.name, reg.wrapname))
   end
   table.insert(txt, '{NULL, NULL}')
   table.insert(txt, '};')
   table.insert(txt, '')   
   self.dispatchregistry = {}
end

interface:print('/* WARNING: autogenerated file */')
interface:print('')

local reals = {ByteTensor='byte',
               CharTensor='char',
               ShortTensor='short',
               IntTensor='int',
               LongTensor='long',
               FloatTensor='float',
               DoubleTensor='double'}

for _,Tensor in ipairs({"ByteTensor", "CharTensor",
                            "ShortTensor", "IntTensor", "LongTensor",
                            "FloatTensor", "DoubleTensor"}) do

   local real = reals[Tensor]

   function interface.luaname2wrapname(self, name)
      return string.format('torch_%s_%s', Tensor, name)
   end

   local function cname(name)
      return string.format('TH%s_%s', Tensor, name)
   end

   local function lastdim(argn)
      return function(arg)
                return string.format("TH%s_nDimension(%s)", Tensor, arg.args[argn]:carg())
             end
   end
   
   interface:wrap("zero",
                  cname("zero"),
                  {{name=Tensor, returned=true}})

   interface:wrap("fill",
                  cname("fill"),
                  {{name=Tensor, returned=true},
                   {name=real}})

   interface:wrap("zeros",
                  cname("zeros"),
                  {{name=Tensor, default=true, returned=true},
                   {name="LongArg"}})

   interface:wrap("ones",
                  cname("ones"),
                  {{name=Tensor, default=true, returned=true},
                   {name="LongArg"}})

   interface:wrap("reshape",
                  cname("reshape"),
                  {{name=Tensor, default=true, returned=true},
                   {name=Tensor},
                   {name="LongArg"}})

   interface:wrap("dot",
                  cname("dot"),
                  {{name=Tensor},
                   {name=Tensor},
                   {name=real, creturned=true}})

   for _,name in ipairs({"minall", "maxall", "sumall"}) do
      interface:wrap(name,
                     cname(name),
                     {{name=Tensor},            
                      {name=real, creturned=true}})
   end

   interface:wrap("add",
                  cname("add"),
                  {{name=Tensor, default=true, returned=true},
                   {name=Tensor},
                   {name=real}},
                  cname("cadd"),
                  {{name=Tensor, default=true, returned=true},
                   {name=Tensor},
                   {name=real, default=1},
                   {name=Tensor}})

   interface:wrap("mul",
                  cname("mul"),
                  {{name=Tensor, default=true, returned=true},
                   {name=Tensor},
                   {name=real}})

   interface:wrap("div",
                  cname("div"),
                  {{name=Tensor, default=true, returned=true},
                   {name=Tensor},
                   {name=real}})

   interface:wrap("cmul",
                  cname("cmul"),
                  {{name=Tensor, default=true, returned=true},
                   {name=Tensor},
                   {name=Tensor}})

   interface:wrap("cdiv",
                  cname("cdiv"),
                  {{name=Tensor, default=true, returned=true},
                   {name=Tensor},
                   {name=Tensor}})

   interface:wrap("addcmul",
                  cname("addcmul"),
                  {{name=Tensor, default=true, returned=true},
                   {name=Tensor},
                   {name=real, default=1},
                   {name=Tensor},
                   {name=Tensor}})

   interface:wrap("addcdiv",
                  cname("addcdiv"),
                  {{name=Tensor, default=true, returned=true},
                   {name=Tensor},
                   {name=real, default=1},
                   {name=Tensor},
                   {name=Tensor}})

   for _,name in ipairs({"addmv", "addmm", "addr"}) do
      interface:wrap(name,
                     cname(name),
                     {{name=Tensor, default=true, returned=true},
                      {name=real, default=1},
                      {name=Tensor},
                      {name=real, default=1},
                      {name=Tensor},
                      {name=Tensor}})
   end

   interface:wrap("numel",
                  cname("numel"),
                  {{name=Tensor},
                   {name=real, creturned=true}})

   for _,name in ipairs({"sum", "prod", "cumsum", "cumprod"}) do
      interface:wrap(name,
                     cname(name),
                     {{name=Tensor, default=true, returned=true},
                      {name=Tensor},
                      {name="index", default=lastdim(2)}})
   end

   interface:wrap("min",
                  cname("min"),
                  {{name=Tensor, default=true, returned=true},
                   {name="IndexTensor", default=true, returned=true},
                   {name=Tensor},
                   {name="index", default=lastdim(3)}})

   interface:wrap("max",
                  cname("max"),
                  {{name=Tensor, default=true, returned=true},
                   {name="IndexTensor", default=true, returned=true},
                   {name=Tensor},
                   {name="index", default=lastdim(3)}})

   interface:wrap("trace",
                  cname("trace"),
                  {{name=Tensor},
                   {name=real, creturned=true}})

   interface:wrap("cross",
                  cname("cross"),
                  {{name=Tensor, default=true, returned=true},
                   {name=Tensor},
                   {name=Tensor},
                   {name="index", default=0}})

   interface:wrap("diag",
                  cname("diag"),
                  {{name=Tensor, default=true, returned=true},
                   {name=Tensor},
                   {name="long", default=0}})

   interface:wrap("eye",
                  cname("eye"),
                  {{name=Tensor, default=true, returned=true},
                   {name="long"},
                   {name="long", default=0}})

   interface:wrap("range",
                  cname("range"),
                  {{name=Tensor, default=true, returned=true},
                   {name=real},
                   {name=real},
                   {name=real, default=1}})

   interface:wrap("randperm",
                  cname("randperm"),
                  {{name=Tensor, default=true, returned=true, userpostcall=function(arg)
                                                                              return string.format("TH%s_add(%s, %s, 1);", Tensor, arg:carg(), arg:carg())
                                                                           end},
                   {name="long"}})

   interface:wrap("sort",
                  cname("sort"),
                  {{name=Tensor, default=true, returned=true},
                   {name="IndexTensor", default=true, returned=true},
                   {name=Tensor},
                   {name="index", default=lastdim(3)},
                   {name="boolean", default=0}})


   interface:wrap("tril",
                  cname("tril"),
                  {{name=Tensor, default=true, returned=true},
                   {name=Tensor},
                   {name="int", default=0}})

   interface:wrap("triu",
                  cname("triu"),
                  {{name=Tensor, default=true, returned=true},
                   {name=Tensor},
                   {name="int", default=0}})

   interface:wrap("cat",
                  cname("cat"),
                  {{name=Tensor, default=true, returned=true},
                   {name=Tensor},
                   {name=Tensor},
                   {name="index", default=lastdim(2)}})

   if Tensor == 'FloatTensor' or Tensor == 'DoubleTensor' then

      interface:wrap("mean",
                     cname("mean"),
                     {{name=Tensor, default=true, returned=true},
                      {name=Tensor},
                      {name="index", default=lastdim(2)}})

      interface:wrap("std",
                     cname("std"),
                     {{name=Tensor, default=true, returned=true},
                      {name=Tensor},
                      {name="index", default=lastdim(2)},
                      {name="boolean", default=false}})

      interface:wrap("var",
                     cname("var"),
                     {{name=Tensor, default=true, returned=true},
                      {name=Tensor},
                      {name="index", default=lastdim(2)},
                      {name="boolean", default=false}})

      interface:wrap("norm",
                     cname("norm"),
                     {{name=Tensor},
                      {name=real, default=2},
                      {name=real, creturned=true}})

      interface:wrap("dist",
                     cname("dist"),
                     {{name=Tensor},
                      {name=Tensor},
                      {name=real, default=2},
                      {name=real, creturned=true}})

      for _,name in ipairs({"meanall", "varall", "stdall"}) do
         interface:wrap(name,
                        cname(name),
                        {{name=Tensor},
                         {name=real, creturned=true}})
      end

      interface:wrap("linspace",
                     cname("linspace"),
                     {{name=Tensor, default=true, returned=true},
                      {name=real},
                      {name=real},
                      {name="long", default=100}})

      interface:wrap("logspace",
                     cname("logspace"),
                     {{name=Tensor, default=true, returned=true},
                      {name=real},
                      {name=real},
                      {name="long", default=100}})

      for _,name in ipairs({"log", "log1p", "exp",
                            "cos", "acos", "cosh",
                            "sin", "asin", "sinh",
                            "tan", "atan", "tanh",
                            "sqrt",
                            "ceil", "floor",
                            "abs"}) do

         interface:wrap(name,
                        cname(name),
                        {{name=Tensor, default=true, returned=true},
                         {name=Tensor}},
                        name,
                        {{name=real},
                         {name=real, creturned=true}})
         
      end

      interface:wrap("pow",
                     cname("pow"),
                     {{name=Tensor, default=true, returned=true},
                      {name=Tensor},
                      {name=real}},
                     "pow",
                     {{name=real},
                      {name=real},
                      {name=real, creturned=true}})

      interface:wrap("rand",
                     cname("rand"),
                     {{name=Tensor, default=true, returned=true},
                      {name="LongArg"}})

      interface:wrap("randn",
                     cname("rand"),
                     {{name=Tensor, default=true, returned=true},
                      {name="LongArg"}})

   end

   interface:register(string.format("torch_%sMath__", Tensor))

   interface:print(string.gsub([[
static void torch_TensorMath_init(lua_State *L)
{
  torch_Tensor_id = luaT_checktypename2id(L, "torch.Tensor");
  torch_LongStorage_id = luaT_checktypename2id(L, "torch.LongStorage");

  /* register everything into the "torch" field of the tensor metaclass */
  luaT_pushmetaclass(L, torch_Tensor_id);
  lua_pushstring(L, "torch");
  lua_newtable(L);
  luaL_register(L, NULL, torch_TensorMath__);
  lua_rawset(L, -3);
  lua_pop(L, 1);
}
]], 'Tensor', Tensor))
end

interface:dispatchregister("torch_TensorMath__")

if arg[1] then
   interface:tofile(arg[1])
else
   interface:tostdio()
end
