# FFTW_INCLUDE_DIR = fftw3.h
# FFTW_LIBRARIES = libfftw3.a
# FFTW_FOUND = true if FFTW3 is found

FIND_PATH(FFTW_INCLUDE_DIR fftw3.h)# ${QMC_INCLUDE_PATHS})
FIND_LIBRARY(FFTWD_LIBRARIES fftw3 fftw3f)# ${QMC_LIBRARY_PATHS})
FIND_LIBRARY(FFTWF_LIBRARIES fftw3f)# ${FFTW_LIBRARY_DIRS})

SET(FFTW_FOUND FALSE)
IF(FFTW_INCLUDE_DIR AND FFTWD_LIBRARIES AND FFTWF_LIBRARIES)
  SET(FFTW_LIBRARIES "${FFTWD_LIBRARIES};${FFTWF_LIBRARIES}")
  MESSAGE(STATUS "FFTW_INCLUDE_DIR=${FFTW_INCLUDE_DIR}")
  MESSAGE(STATUS "FFTW_LIBRARIES=${FFTW_LIBRARIES}")
  SET(FFTW_FOUND TRUE)
ENDIF()

MARK_AS_ADVANCED(
   FFTW_INCLUDE_DIR
   FFTW_LIBRARIES
   FFTW_FOUND
)
