require 'wrap'

cinterface = wrap.cinterface

local function lname(name)
   return string.format('lab_(%s)', name)
end

local function cname(name)
   return string.format('THLab_(%s)', name)
end

print('/* WARNING: autogenerated file */')
print()

cinterface(lname("zero"),
           cname("zero"),
           {{name="Tensor", returned=true}})

cinterface(lname("fill"),
           cname("fill"),
           {{name="Tensor", returned=true},
            {name="real"}})

cinterface(lname("dot"),
           cname("dot"),
           {{name="Tensor"},
            {name="Tensor"},
            {name="real", creturned=true}})

for _,name in ipairs({"minall", "maxall", "sumall"}) do
   cinterface(lname(name),
              cname(name),
              {{name="Tensor"},            
               {name="real", creturned=true}})
end

cinterface(lname("add"),
           cname("add"),
           {{name="Tensor", default=true, returned=true},
            {name="Tensor"},
            {name="real"}},
           cname("cadd"),
           {{name="Tensor", default=true, returned=true},
            {name="Tensor"},
            {name="real", default=1},
            {name="Tensor"}})

cinterface(lname("mul"),
           cname("mul"),
           {{name="Tensor", default=true, returned=true},
            {name="Tensor"},
            {name="real"}})

cinterface(lname("div"),
           cname("div"),
           {{name="Tensor", default=true, returned=true},
            {name="Tensor"},
            {name="real"}})

cinterface(lname("cmul"),
           cname("cmul"),
           {{name="Tensor", default=true, returned=true},
            {name="Tensor"},
            {name="Tensor"}})

cinterface(lname("cdiv"),
           cname("cdiv"),
           {{name="Tensor", default=true, returned=true},
            {name="Tensor"},
            {name="Tensor"}})

cinterface(lname("addcmul"),
           cname("addcmul"),
           {{name="Tensor", default=true, returned=true},
            {name="Tensor"},
            {name="real", default=1},
            {name="Tensor"},
            {name="Tensor"}})

cinterface(lname("addcdiv"),
           cname("addcdiv"),
           {{name="Tensor", default=true, returned=true},
            {name="Tensor"},
            {name="real", default=1},
            {name="Tensor"},
            {name="Tensor"}})

for _,name in ipairs({"addmv", "addmm", "addr"}) do
   cinterface(lname(name),
              cname(name),
              {{name="Tensor", default=true, returned=true},
               {name="real", default=1},
               {name="Tensor"},
               {name="real", default=1},
               {name="Tensor"},
               {name="Tensor"}})
end

cinterface(lname("numel"),
           cname("numel"),
           {{name="Tensor"},
            {name="real", creturned=true}})

for _,name in ipairs({"sum", "prod", "cumsum", "cumprod"}) do
   cinterface(lname(name),
              cname(name),
              {{name="Tensor", default=true, returned=true},
               {name="Tensor"},
               {name="integer", default=0}})
end

cinterface(lname("min"),
           cname("min"),
           {{name="Tensor", default=true, returned=true},
            {name="LongTensor", default=true, returned=true},
            {name="Tensor"},
            {name="integer", default=0}})

cinterface(lname("max"),
           cname("max"),
           {{name="Tensor", default=true, returned=true},
            {name="LongTensor", default=true, returned=true},
            {name="Tensor"},
            {name="integer", default=0}})

cinterface(lname("trace"),
           cname("trace"),
           {{name="Tensor"},
            {name="real", creturned=true}})

cinterface(lname("cross"),
           cname("cross"),
           {{name="Tensor", default=true, returned=true},
            {name="Tensor"},
            {name="Tensor"},
            {name="integer", default=0}})

cinterface(lname("diag"),
           cname("diag"),
           {{name="Tensor", default=true, returned=true},
            {name="Tensor"},
            {name="long", default=0}})

cinterface(lname("eye"),
           cname("eye"),
           {{name="Tensor", default=true, returned=true},
            {name="long"},
            {name="long", default=0}})

cinterface(lname("range"),
           cname("range"),
           {{name="Tensor", default=true, returned=true},
            {name="real"},
            {name="real"},
            {name="real", default=0}})

cinterface(lname("randperm"),
           cname("randperm"),
           {{name="Tensor", default=true, returned=true},
            {name="long"}})

cinterface(lname("sort"),
           cname("sort"),
           {{name="Tensor", default=true, returned=true},
            {name="LongTensor", default=true, returned=true},
            {name="Tensor"},
            {name="integer", default=0},
            {name="boolean", default=0}})


cinterface(lname("tril"),
           cname("tril"),
           {{name="Tensor", default=true, returned=true},
            {name="Tensor"},
            {name="integer", default=0}})

cinterface(lname("triu"),
           cname("triu"),
           {{name="Tensor", default=true, returned=true},
            {name="Tensor"},
            {name="integer", default=0}})

cinterface(lname("cat"),
           cname("cat"),
           {{name="Tensor", default=true, returned=true},
            {name="Tensor"},
            {name="Tensor"},
            {name="integer", default=0}})

print("#if defined(TH_REAL_IS_FLOAT) || defined(TH_REAL_IS_DOUBLE)")

cinterface(lname("mean"),
           cname("mean"),
           {{name="Tensor", default=true, returned=true},
            {name="Tensor"},
            {name="integer", default=0}})

cinterface(lname("std"),
           cname("std"),
           {{name="Tensor", default=true, returned=true},
            {name="Tensor"},
            {name="integer", default=0},
            {name="boolean", default=false}})

cinterface(lname("var"),
           cname("var"),
           {{name="Tensor", default=true, returned=true},
            {name="Tensor"},
            {name="integer", default=0},
            {name="boolean", default=false}})

cinterface(lname("norm"),
           cname("norm"),
           {{name="Tensor"},
            {name="real", default=2},
            {name="real", creturned=true}})

cinterface(lname("dist"),
           cname("dist"),
           {{name="Tensor"},
            {name="Tensor"},
            {name="real", default=2},
            {name="real", creturned=true}})

for _,name in ipairs({"meanall", "varall", "stdall"}) do
   cinterface(lname(name),
              cname(name),
              {{name="Tensor"},
               {name="real", creturned=true}})
end

cinterface(lname("linspace"),
           cname("linspace"),
           {{name="Tensor", default=true, returned=true},
            {name="real"},
            {name="real"},
            {name="long", default=100}})

cinterface(lname("logspace"),
           cname("logspace"),
           {{name="Tensor", default=true, returned=true},
            {name="real"},
            {name="real"},
            {name="long", default=100}})

for _,name in ipairs({"log", "log1p", "exp",
                      "cos", "acos", "cosh",
                      "sin", "asin", "sinh",
                      "tan", "atan", "tanh",
                      "sqrt",
                      "ceil", "floor",
                      "abs"}) do

   cinterface(lname(name),
              cname(name),
              {{name="Tensor", default=true, returned=true},
               {name="Tensor"}},
              name,
              {{name="real"},
               {name="real", creturned=true}})
   
end

cinterface(lname("pow"),
           cname("pow"),
           {{name="Tensor", default=true, returned=true},
            {name="Tensor"},
            {name="real"}},
           "pow",
           {{name="real"},
            {name="real"},
            {name="real", creturned=true}})

print("#endif")
